doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

        types:
            uuid_id: 'App\Model\Shared\Domain\Entity\ValueObject\IdType'
            user_user_email: 'App\Model\User\Domain\Entity\EmailType'
            images_author_status: 'App\Model\Images\Domain\Entity\Author\StatusType'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/User/Domain/Entity'
                prefix: 'App\Model\User\Domain\Entity'
                alias: User
            Images:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/Images/Domain/Entity'
                prefix: 'App\Model\Images\Domain\Entity'
                alias: Images

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
