twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_3_layout.html.twig']

    globals:
        author_image_directory: '/uploads/author/'

when@test:
    twig:
        strict_variables: true
